### ISSUE TITLE
Publish new version on npm

### ISSUE THREAD

**Issue by piranna** [GitbookIO/plugin-autocover#7]
Latest published version is 1.2.1, but it doesn't have any of the svg cover features.

**Comment by piranna** [comment]
Any update on this?

**Comment by piranna** [comment]
I've checked it and it's not possible to set a GitHub repository as source of gitbook plugins, and since gitbook webside don't exec npm install, there's no other way to use SVG templates from the web.

**Comment by piranna** [comment]
Any update on this?

**Comment by piranna** [comment]
There are several forks that update the version of node-canvas since it doesn't work on Node.js 4. @SamyPesse, could you be able to publish an updated version? If not it's impossible to use a recent version of Node.js due to how GitBook install the plugins directly from npm... :-(

**Comment by TheLonelyGhost** [comment]
New version has been published. It looks like this project is unmaintained, so it's at @piranna's discretion to close the issue.

**Comment by piranna** [comment]
I would maintain it if @SamyPesse give me permissions here and on npm to upload new versiones.

**Comment by SamyPesse** [comment]
@piranna I've added you to NPM, you already have write access to this repository.
